version: "3.7"
services:
    app:
        build:
            args:
                user: gustavasconcelos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: uropad
        container_name: uropad-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        networks:
            - uropad

    db:
        image: mysql:8.0
        container_name: uropad-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: uropad_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root1234
            MYSQL_USER: uropadUser
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql-volume:/var/lib/mysql
        networks:
            - uropad

networks:
    uropad:
        driver: bridge
volumes:
    mysql-volume:
        driver: local
